heat_template_version: '2013-05-23'
description: |
  Template which creates single instance
parameters:
  InstanceType:
    type: string
  ImageId:
    type: string
  network:
    type: string
resources:
  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: network}

  Server:
    type: OS::Nova::Server
    properties:
      name: ost1-test_heat
      image: {get_param: ImageId}
      flavor: {get_param: InstanceType}
      flavor_update_policy: REPLACE
      networks:
          - port: {get_resource: port}
outputs:
  servers:
    value:
      get_resource: Server
